# Generated by Django 2.2.3 on 2019-07-16 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('meeting_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('ateend', models.IntegerField(blank=True, default=0)),
                ('late', models.IntegerField(blank=True, default=0)),
                ('absent', models.IntegerField(blank=True, default=0)),
                ('meetings', models.ManyToManyField(through='attendance.Check', to='attendance.Meeting')),
            ],
        ),
        migrations.AddField(
            model_name='check',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Meeting'),
        ),
        migrations.AddField(
            model_name='check',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Person'),
        ),
    ]
