# Generated by Django 2.2.3 on 2019-07-16 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='ateend',
            new_name='attend',
        ),
    ]
