# Generated by Django 2.2.3 on 2019-07-16 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20190716_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendance.Meeting')),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='meetings',
        ),
        migrations.DeleteModel(
            name='Check',
        ),
        migrations.AddField(
            model_name='checking',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendance.Person'),
        ),
    ]
