# Generated by Django 2.2.3 on 2019-07-16 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20190716_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checking',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Meeting'),
        ),
        migrations.AlterField(
            model_name='checking',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Person'),
        ),
    ]
