# Generated by Django 2.2.3 on 2019-07-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_person_membernumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='checking',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
